server:
  port: 8083
spring:
  application:
    name: search-service
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.120:9300
  jackson:
    default-property-inclusion: non_null  #只输出不为空的字段，过滤为null的字段
  rabbitmq:
    host: 192.168.1.120
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 #服务拉取时间

  instance:
    lease-expiration-duration-in-seconds: 15 # 15秒不发送就过期
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳