server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.1.120
  data:
    mongodb:
      port: 27017
      host: 192.168.1.120
      database: my_test
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 #拉去服务时间
  instance:
    lease-expiration-duration-in-seconds: 15  #心跳过期时间
    lease-renewal-interval-in-seconds: 5 #心跳时间

leyou:
  jwt:
    pubKeyPath: F:\ideaWork\leyouProject\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN