#服务端
server:
  port: 8085
spring:
  application:
    name: leyou-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.1.120
  rabbitmq:
    host: 192.168.1.120
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 15 # 10秒不发送就过期

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
  type-aliases-package: com.leyou.user.pojo